In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn import svm

In [2]:
fake=pd.read_csv(r"C:\Users\Dhrub\Downloads\archive (19)\Fake.csv")
real=pd.read_csv(r"C:\Users\Dhrub\Downloads\archive (19)\True.csv")

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
real.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake["label"] = 0
real["label"] = 1

df = pd.concat([fake, real])

In [6]:
df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [7]:
df['subject'].value_counts()

subject
politicsNews       11272
worldnews          10145
News                9050
politics            6841
left-news           4459
Government News     1570
US_News              783
Middle-east          778
Name: count, dtype: int64

In [8]:
df["text"] = df["text"].str.lower()
import re
import string
#remove punctuation
df['text'] = df['text'].str.translate(str.maketrans('', '', string.punctuation))
#remove numbers
df['text'] = df['text'].str.replace(r'\d+', '', regex=True)
# Remove HTML tags
df['text'] = df['text'].str.replace(r'<.*?>', '', regex=True)
# Remove URLs
df['text'] = df['text'].str.replace(r'http\S+|www\S+', '', regex=True)
#Remove emojis
df['text'] = df['text'].str.replace(r'[\U00010000-\U0010ffff]','', regex=True)

In [9]:
df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,donald trump just couldn t wish all americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,house intelligence committee chairman devin nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,on friday it was revealed that former milwauke...,News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,on christmas day donald trump announced that h...,News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,pope francis used his annual christmas day mes...,News,"December 25, 2017",0

In [10]:
st=set(stopwords.words('english'))

In [11]:
df['text'] = df['text'].apply(lambda x: " ".join([w for w in x.split() if w not in st]))

In [12]:
df['text']

0        donald trump wish americans happy new year lea...
1        house intelligence committee chairman devin nu...
2        friday revealed former milwaukee sheriff david...
3        christmas day donald trump announced would bac...
4        pope francis used annual christmas day message...
                               ...
21412    brussels reuters nato allies tuesday welcomed ...
21413    london reuters lexisnexis provider legal regul...
21414    minsk reuters shadow disused sovietera factori...
21415    moscow reuters vatican secretary state cardina...
21416    jakarta reuters indonesia buy sukhoi fighter j...
Name: text, Length: 44898, dtype: object

In [13]:
X=df['text']
y=df['label']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
X_train

7404     washington reuters us president barack obama p...
17270    jerusalem reuters israel monday approved build...
603      north korea true present threat world responde...
8521     windham nh reuters republican donald trump sat...
7102     sarah palin must powerful drugs delivered ramb...
                               ...
11284
21251    londontokyo reuters british prime minister the...
14677    berlin reuters chancellor angela merkel said g...
860      jesus fcking christ president moron satisfied ...
15795    toast bigger trouble thought much whole thing ...
Name: text, Length: 30081, dtype: object

In [16]:
tf=TfidfVectorizer()
X_train_tf=tf.fit_transform(X_train)
X_test_tf=tf.transform(X_test)

In [17]:
lb=LogisticRegression()
lb.fit(X_train_tf,y_train)
y_p3=lb.predict(X_test_tf)
accuracy_score(y_p3,y_test)

0.9895390429911588

In [18]:
print(confusion_matrix(y_test, y_p3))

[[7685   93]
 [  62 6977]]

In [19]:
print(classification_report(y_test, y_p3))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7778
           1       0.99      0.99      0.99      7039

    accuracy                           0.99     14817
   macro avg       0.99      0.99      0.99     14817
weighted avg       0.99      0.99      0.99     14817

In [20]:
user_news = input("Enter news article: ")

user_vector = tf.transform([user_news])

prediction = lb.predict(user_vector)
probability = lb.predict_proba(user_vector)

if prediction[0] == 0:
    print("Fake News")
    print("Confidence:", round(probability[0][0] * 100, 2), "%")
else:
    print("Real News")
    print("Confidence:", round(probability[0][1] * 100, 2), "%")

Enter news article:  BREAKING: Scientists confirm that drinking 10 cups of coffee per day makes humans live up to 150 years. The discovery has shocked medical experts worldwide and governments are considering making coffee mandatory.

Fake News
Confidence: 63.53 %

In [29]:
import joblib

joblib.dump(lb, "fake_news_model.pkl")
joblib.dump(tf, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [21]:
# mb=MultinomialNB()
# mb.fit(X_train_tf,y_train)
# y_p1=mb.predict(X_test_tf)
# accuracy_score(y_p1,y_test)

In [22]:
# print(confusion_matrix(y_test, y_p1))

In [23]:
# sb=svm.SVC()
# sb.fit(X_train_tf,y_train)
# y_p3=sb.predict(X_test_tf) 
# accuracy_score(y_p3,y_test)

In [24]:
# cv=CountVectorizer()
# X_train_cv=cv.fit_transform(X_train)
# X_test_cv=cv.transform(X_test)

In [25]:
# mb=MultinomialNB()
# mb.fit(X_train_cv,y_train)
# y_p1=mb.predict(X_test_cv)
# accuracy_score(y_p1,y_test)

In [26]:
# lb=LogisticRegression()
# lb.fit(X_train_cv,y_train)
# y_p3=lb.predict(X_test_cv)
# accuracy_score(y_p3,y_test)

In [27]:
# sb=svm.SVC()
# sb.fit(X_train_cv,y_train)
# y_p3=sb.predict(X_test_cv)
# accuracy_score(y_p3,y_test)